roles/mail/files/aliases

Per questions on IRC. @Arcane21 can't be added, as I have no idea what his email address is.

Add staff(at)orain(dot)org alias + one for me

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

As requested here:
http://drunkardswalkforums.yuku.com/sreply/127702/All-The-Tropes-Wiki-Project-Part-IV

Adding permissions for poserdazfreebies wiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Was causing permissions issues and spam problems on Anthony's wikis

removed "member" right add/remove

---

roles/nginx/templates/sites-enabled/all.j2

Validated with http://www.cspplayground.com/csp_validator
Removes asirra
Removes http / https specification

Simplify CSP policy

---

roles/mediawiki/files/localsettings/LocalExtensions.php

added CharInsert and EmbedVideo extensions for gamewiki

gamewiki extensions

---

roles/mediawiki/files/localsettings/LocalExtensions.php

• added CreateBox
• added EmbedVideo

cwsplanetwiki extensions

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Please perform pull request #543 before this one.

enable wmgUseTimedMediaHandler on extloadwiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

granbluefantasywiki changes

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Reverts Orain/ansible-playbook#549
Ugh, something went wrong.

Revert "enabled TimedMediaHandler on lovelivesiftwwiki"

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Reverts Orain/ansible-playbook#550

Revert "Revert "enabled TimedMediaHandler on lovelivesiftwwiki""

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Enabled:
• DPLforum
• Echo (and Thanks)
• Quiz
• Tabber

memewiki extensions

---

roles/mediawiki/files/localsettings/LocalExtensions.php

added an option to enable/disable DismissableSiteNotice

created $wmgUseDismissableSiteNotice

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

added an option to enable/disable DismissableSiteNotice
Make sure to do #566 before this one.

created wmgUseDismissableSiteNotice setting

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

• changed local timezone
• changed meta namespace name

lovelivesiftwwiki settings

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

• Added logo
• Added namespace alias

ironperfectionwiki changes

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

I think it's causing issues with Collection.

disabled sidebar cache on shepherdjournalwiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

added "bureaucrat" level protection for quantixhl2rpwiki and ironperfectionwiki both owned by NDKilla.
also added namespace aliases for quantixhl2rpwiki

NDKilla's localsettings patch (see desc)

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

+disable anon editing on squaredanceideaswiki

disable anon editing on squaredanceideaswiki

---

roles/base/files/hosts
roles/base/files/nrpe.cfg
roles/base/tasks/files.yml
roles/base/tasks/ufw.yml
roles/nagios/files/conf.d/hosts.cfg
roles/nagios/files/conf.d/services.cfg
roles/nginx/files/sites-enabled-agnostic/prod11.orain.org
roles/nginx/files/sites-enabled-agnostic/prod8.orain.org
roles/nginx/files/sites-enabled-agnostic/prod9.orain.org

Tested on prod10 and no errors, site also stays up...

Remove public ips

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Reverts Orain/ansible-playbook#619

Revert "test group overrides on quantixdevwiki"

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

manually setting group over-rides on this wiki because of issues with perms

quantixdev fix

---

roles/mediawiki/files/localsettings/LocalExtensions.php
roles/mediawiki/files/localsettings/LocalSettings.php.j2

quantixdevwiki groups,
first robotix groups
anon editing on krswwiki,
copyrights on anarchism wiki
travis CI please

several wikis requests

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2
roles/nginx/templates/sites-enabled/all.j2

Added entries to point wiki.rohbio.net to rohbiotik.orain.org (DB name rohbiotikwiki).

Custom domain wiki.rohbio.net

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2
roles/nginx/templates/sites-enabled/all.j2

Since the change is not working.

Revert "Custom domain wiki.rohbio.net"

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

I'm not very sure if I should remove this..

Rem stuff for proper working of deguwiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php
roles/mediawiki/files/localsettings/LocalSettings.php.j2

• enable EmbedVideo extension
• disable anon editing
• add three namespaces
• enable subpages for one of the namespaces
• change timezone

tomegkozlekedowiki changes

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

We don't make much use, if any, of Collection or TimedMediaHandler

removed ext from ATT

---

roles/mediawiki/vars/main.yml

Adding Spoilers extensions

---

roles/mediawiki/vars/main.yml

Reverts Orain/ansible-playbook#654
Going to fork the extension

Revert "Adding Spoilers extensions"

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Commenting out rarely used extensions from ATT

remove ext from ATT

---

roles/mediawiki/vars/main.yml

https://meta.orain.org/wiki/User_talk:NDKilla#Spoilers_extensions

Adding Spoilers extension again per NDKilla

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Adding Spoilers extension

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Adding spoilers extension to gamewiki per request https://meta.orain.org/wiki/Request_features

Adding Spoilers extension to gamewiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Adding Ext.CharInset+CodeEditor to linuxunixwi

---

roles/mediawiki/vars/main.yml

Downloading TemplateData extension

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Adding Extension ImageMap to creersonarbrewiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php

adding TemplateData

---

roles/mediawiki/files/localsettings/LocalExtensions.php

add Thanks ext to farmsimwiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

adding custom logo to farmsimwiki.

---

roles/mediawiki/files/localsettings/LocalExtensions.php

+adding echo extension to farmingsimulatorwiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Allow pdf uploads to internalwiki

Add pdf to internalwiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php

+add Deletebatch ext. to farmsimwiki

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Deleting as the wiki has been deleted.

Deleting frmodamobwiki stuff (wiki deleted)

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Functionality appears broken at present

disabling ext on ATT

---

roles/mediawiki/vars/main.yml

All of which have commits in later version which should fix some current issues on Orain

changed several extensions to use master branch

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

As no one seems to be handling the request i'll do it. Could someone please mark it as done on the page (i am currently blocked)?

add izanagiwiki favicon

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Please notify the user (as I am blocked) and make the wiki un-private (per request)

add disable anon editing per request

---

roles/mediawiki/files/localsettings/LocalExtensions.php

Please notify user (as I am blocked)

add imagemap to tunavork per request

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

Request dating 28 NOVEMBER 2014!! @NDKilla @addshore

add per request

---

roles/mediawiki/vars/main.yml

install latest version of WIkiSEO (per addshore)

---

roles/mariadb/templates/debian.cnf.j2

Please DO NOT MERGE!! except if you are sure this is correct!! @addshore 
This is how it was fixed for Miraheze.

to fix founder rights! DO NOT MERGE IF YOU ARE NOT SURE

---

roles/mediawiki/vars/main.yml

download Memento

---

roles/mediawiki/vars/main.yml

Reverts Orain/ansible-playbook#716

Revert "download Memento"

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

disable anon editing on studieveiledermedisinwiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php

add MU and MV extensions to maquetaschillewiki

---

roles/mediawiki/files/localsettings/LocalExtensions.php

add MobileFrontend+Mantle to rachopedia per req

---

roles/mediawiki/files/localsettings/LocalSettings.php.j2

should be for administrators only but I do not know how
@NDKilla (also please make wiki public) @addshore

disable anon editing rachopedia

---

roles/mediawiki/files/localsettings/LocalExtensions.php

@addshore @NDKilla 
I remember adding this a month or two ago, and I did mark it done..

add MCsearch per request (should have been added)
